repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.4.0"
    hooks:
      - id: check-merge-conflict
      - id: debug-statements

  - repo: local

    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length=200, --target-version=py311]

      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [python]
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: [
          "--ignore=E203,W503,FI10,FI11,FI12,FI13,FI14,FI15,FI16,FI17,FI58,PT013",
          "--per-file-ignores=eatpoint/manage.py:E501, eatpoint/eatpoint/settings.py:E501"
        ]

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]