version: '3.0'
services:
  db:
    image: postgres:12.4
    restart: always
    container_name: db
    volumes:
      - ./persistentdata/db:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    container_name: backend
    restart: always
    image: valentaine98/eatpoint-backend:latest
    expose:
      - 8000
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./persistentdata/certbot/conf:/etc/letsencrypt
      - ./persistentdata/certbot/www:/var/www/certbot
      - static_value:/var/www/static
      - media_value:/var/www/media
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    container_name: certbot
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt # <--here
      - ./persistentdata/certbot/www:/var/www/certbot # <--here
    depends_on:
      - nginx

volumes:
  static_value:
  media_value: